### ISSUE TITLE
ICO?

### ISSUE THREAD

**Issue by mamigot** [mafshar/ssd-pose-estimation#2]
When's the initial coin offering for this?
![](https://github.com/mafshar/ssd-pose-estimation/raw/master/data_archive/init_data/figure_1_reg.png)

**Comment by radhikamattoo** [comment]
1 bitcoin @mamigot

**Comment by ayrnee** [comment]
http://dogecoin.com/

**Comment by mafshar** [comment]
Right then folks, I’m gonna close this issue since we have come to an understanding about our #ledger

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
